# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'to-watch-list-combine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for to-watch-list-combine
  pod 'SwiftLint'

end
